// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kv.proto

#include "kv.grpc.pb.h"
#include "kv.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char *KVService_method_names[] = {
    "/KVService/Set",
    "/KVService/Get",
    "/KVService/Delete",
};

std::unique_ptr<KVService::Stub>
KVService::NewStub(const std::shared_ptr<::grpc::ChannelInterface> &channel,
                   const ::grpc::StubOptions &options) {
    (void)options;
    std::unique_ptr<KVService::Stub> stub(new KVService::Stub(channel, options));
    return stub;
}

KVService::Stub::Stub(const std::shared_ptr<::grpc::ChannelInterface> &channel,
                      const ::grpc::StubOptions &options)
    : channel_(channel), rpcmethod_Set_(KVService_method_names[0], options.suffix_for_stats(),
                                        ::grpc::internal::RpcMethod::NORMAL_RPC, channel),
      rpcmethod_Get_(KVService_method_names[1], options.suffix_for_stats(),
                     ::grpc::internal::RpcMethod::NORMAL_RPC, channel),
      rpcmethod_Delete_(KVService_method_names[2], options.suffix_for_stats(),
                        ::grpc::internal::RpcMethod::NORMAL_RPC, channel) {
}

::grpc::Status KVService::Stub::Set(::grpc::ClientContext *context, const ::SetRequest &request,
                                    ::SetResponse *response) {
    return ::grpc::internal::BlockingUnaryCall<
        ::SetRequest, ::SetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        channel_.get(), rpcmethod_Set_, context, request, response);
}

void KVService::Stub::async::Set(::grpc::ClientContext *context, const ::SetRequest *request,
                                 ::SetResponse *response, std::function<void(::grpc::Status)> f) {
    ::grpc::internal::CallbackUnaryCall<::SetRequest, ::SetResponse, ::grpc::protobuf::MessageLite,
                                        ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, std::move(f));
}

void KVService::Stub::async::Set(::grpc::ClientContext *context, const ::SetRequest *request,
                                 ::SetResponse *response, ::grpc::ClientUnaryReactor *reactor) {
    ::grpc::internal::ClientCallbackUnaryFactory::Create<::grpc::protobuf::MessageLite,
                                                         ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_Set_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader<::SetResponse> *
KVService::Stub::PrepareAsyncSetRaw(::grpc::ClientContext *context, const ::SetRequest &request,
                                    ::grpc::CompletionQueue *cq) {
    return ::grpc::internal::ClientAsyncResponseReaderHelper::Create<
        ::SetResponse, ::SetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        channel_.get(), cq, rpcmethod_Set_, context, request);
}

::grpc::ClientAsyncResponseReader<::SetResponse> *
KVService::Stub::AsyncSetRaw(::grpc::ClientContext *context, const ::SetRequest &request,
                             ::grpc::CompletionQueue *cq) {
    auto *result = this->PrepareAsyncSetRaw(context, request, cq);
    result->StartCall();
    return result;
}

::grpc::Status KVService::Stub::Get(::grpc::ClientContext *context, const ::GetRequest &request,
                                    ::GetResponse *response) {
    return ::grpc::internal::BlockingUnaryCall<
        ::GetRequest, ::GetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        channel_.get(), rpcmethod_Get_, context, request, response);
}

void KVService::Stub::async::Get(::grpc::ClientContext *context, const ::GetRequest *request,
                                 ::GetResponse *response, std::function<void(::grpc::Status)> f) {
    ::grpc::internal::CallbackUnaryCall<::GetRequest, ::GetResponse, ::grpc::protobuf::MessageLite,
                                        ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, std::move(f));
}

void KVService::Stub::async::Get(::grpc::ClientContext *context, const ::GetRequest *request,
                                 ::GetResponse *response, ::grpc::ClientUnaryReactor *reactor) {
    ::grpc::internal::ClientCallbackUnaryFactory::Create<::grpc::protobuf::MessageLite,
                                                         ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_Get_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader<::GetResponse> *
KVService::Stub::PrepareAsyncGetRaw(::grpc::ClientContext *context, const ::GetRequest &request,
                                    ::grpc::CompletionQueue *cq) {
    return ::grpc::internal::ClientAsyncResponseReaderHelper::Create<
        ::GetResponse, ::GetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        channel_.get(), cq, rpcmethod_Get_, context, request);
}

::grpc::ClientAsyncResponseReader<::GetResponse> *
KVService::Stub::AsyncGetRaw(::grpc::ClientContext *context, const ::GetRequest &request,
                             ::grpc::CompletionQueue *cq) {
    auto *result = this->PrepareAsyncGetRaw(context, request, cq);
    result->StartCall();
    return result;
}

::grpc::Status KVService::Stub::Delete(::grpc::ClientContext *context, const ::DelRequest &request,
                                       ::DelResponse *response) {
    return ::grpc::internal::BlockingUnaryCall<
        ::DelRequest, ::DelResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        channel_.get(), rpcmethod_Delete_, context, request, response);
}

void KVService::Stub::async::Delete(::grpc::ClientContext *context, const ::DelRequest *request,
                                    ::DelResponse *response,
                                    std::function<void(::grpc::Status)> f) {
    ::grpc::internal::CallbackUnaryCall<::DelRequest, ::DelResponse, ::grpc::protobuf::MessageLite,
                                        ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, std::move(f));
}

void KVService::Stub::async::Delete(::grpc::ClientContext *context, const ::DelRequest *request,
                                    ::DelResponse *response, ::grpc::ClientUnaryReactor *reactor) {
    ::grpc::internal::ClientCallbackUnaryFactory::Create<::grpc::protobuf::MessageLite,
                                                         ::grpc::protobuf::MessageLite>(
        stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader<::DelResponse> *
KVService::Stub::PrepareAsyncDeleteRaw(::grpc::ClientContext *context, const ::DelRequest &request,
                                       ::grpc::CompletionQueue *cq) {
    return ::grpc::internal::ClientAsyncResponseReaderHelper::Create<
        ::DelResponse, ::DelRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
        channel_.get(), cq, rpcmethod_Delete_, context, request);
}

::grpc::ClientAsyncResponseReader<::DelResponse> *
KVService::Stub::AsyncDeleteRaw(::grpc::ClientContext *context, const ::DelRequest &request,
                                ::grpc::CompletionQueue *cq) {
    auto *result = this->PrepareAsyncDeleteRaw(context, request, cq);
    result->StartCall();
    return result;
}

KVService::Service::Service() {
    AddMethod(new ::grpc::internal::RpcServiceMethod(
        KVService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC,
        new ::grpc::internal::RpcMethodHandler<KVService::Service, ::SetRequest, ::SetResponse,
                                               ::grpc::protobuf::MessageLite,
                                               ::grpc::protobuf::MessageLite>(
            [](KVService::Service *service, ::grpc::ServerContext *ctx, const ::SetRequest *req,
               ::SetResponse *resp) { return service->Set(ctx, req, resp); },
            this)));
    AddMethod(new ::grpc::internal::RpcServiceMethod(
        KVService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC,
        new ::grpc::internal::RpcMethodHandler<KVService::Service, ::GetRequest, ::GetResponse,
                                               ::grpc::protobuf::MessageLite,
                                               ::grpc::protobuf::MessageLite>(
            [](KVService::Service *service, ::grpc::ServerContext *ctx, const ::GetRequest *req,
               ::GetResponse *resp) { return service->Get(ctx, req, resp); },
            this)));
    AddMethod(new ::grpc::internal::RpcServiceMethod(
        KVService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC,
        new ::grpc::internal::RpcMethodHandler<KVService::Service, ::DelRequest, ::DelResponse,
                                               ::grpc::protobuf::MessageLite,
                                               ::grpc::protobuf::MessageLite>(
            [](KVService::Service *service, ::grpc::ServerContext *ctx, const ::DelRequest *req,
               ::DelResponse *resp) { return service->Delete(ctx, req, resp); },
            this)));
}

KVService::Service::~Service() {
}

::grpc::Status KVService::Service::Set(::grpc::ServerContext *context, const ::SetRequest *request,
                                       ::SetResponse *response) {
    (void)context;
    (void)request;
    (void)response;
    return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVService::Service::Get(::grpc::ServerContext *context, const ::GetRequest *request,
                                       ::GetResponse *response) {
    (void)context;
    (void)request;
    (void)response;
    return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status KVService::Service::Delete(::grpc::ServerContext *context,
                                          const ::DelRequest *request, ::DelResponse *response) {
    (void)context;
    (void)request;
    (void)response;
    return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}