// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kv.proto
#ifndef GRPC_kv_2eproto__INCLUDED
#define GRPC_kv_2eproto__INCLUDED

#include "kv.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class KVService final {
  public:
    static constexpr char const *service_full_name() {
        return "KVService";
    }
    class StubInterface {
      public:
        virtual ~StubInterface() {
        }
        virtual ::grpc::Status Set(::grpc::ClientContext *context, const ::SetRequest &request,
                                   ::SetResponse *response) = 0;
        std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::SetResponse>>
        AsyncSet(::grpc::ClientContext *context, const ::SetRequest &request,
                 ::grpc::CompletionQueue *cq) {
            return std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::SetResponse>>(
                AsyncSetRaw(context, request, cq));
        }
        std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::SetResponse>>
        PrepareAsyncSet(::grpc::ClientContext *context, const ::SetRequest &request,
                        ::grpc::CompletionQueue *cq) {
            return std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::SetResponse>>(
                PrepareAsyncSetRaw(context, request, cq));
        }
        virtual ::grpc::Status Get(::grpc::ClientContext *context, const ::GetRequest &request,
                                   ::GetResponse *response) = 0;
        std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::GetResponse>>
        AsyncGet(::grpc::ClientContext *context, const ::GetRequest &request,
                 ::grpc::CompletionQueue *cq) {
            return std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::GetResponse>>(
                AsyncGetRaw(context, request, cq));
        }
        std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::GetResponse>>
        PrepareAsyncGet(::grpc::ClientContext *context, const ::GetRequest &request,
                        ::grpc::CompletionQueue *cq) {
            return std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::GetResponse>>(
                PrepareAsyncGetRaw(context, request, cq));
        }
        virtual ::grpc::Status Delete(::grpc::ClientContext *context, const ::DelRequest &request,
                                      ::DelResponse *response) = 0;
        std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::DelResponse>>
        AsyncDelete(::grpc::ClientContext *context, const ::DelRequest &request,
                    ::grpc::CompletionQueue *cq) {
            return std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::DelResponse>>(
                AsyncDeleteRaw(context, request, cq));
        }
        std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::DelResponse>>
        PrepareAsyncDelete(::grpc::ClientContext *context, const ::DelRequest &request,
                           ::grpc::CompletionQueue *cq) {
            return std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::DelResponse>>(
                PrepareAsyncDeleteRaw(context, request, cq));
        }
        class async_interface {
          public:
            virtual ~async_interface() {
            }
            virtual void Set(::grpc::ClientContext *context, const ::SetRequest *request,
                             ::SetResponse *response, std::function<void(::grpc::Status)>) = 0;
            virtual void Set(::grpc::ClientContext *context, const ::SetRequest *request,
                             ::SetResponse *response, ::grpc::ClientUnaryReactor *reactor) = 0;
            virtual void Get(::grpc::ClientContext *context, const ::GetRequest *request,
                             ::GetResponse *response, std::function<void(::grpc::Status)>) = 0;
            virtual void Get(::grpc::ClientContext *context, const ::GetRequest *request,
                             ::GetResponse *response, ::grpc::ClientUnaryReactor *reactor) = 0;
            virtual void Delete(::grpc::ClientContext *context, const ::DelRequest *request,
                                ::DelResponse *response, std::function<void(::grpc::Status)>) = 0;
            virtual void Delete(::grpc::ClientContext *context, const ::DelRequest *request,
                                ::DelResponse *response, ::grpc::ClientUnaryReactor *reactor) = 0;
        };
        typedef class async_interface experimental_async_interface;
        virtual class async_interface *async() {
            return nullptr;
        }
        class async_interface *experimental_async() {
            return async();
        }

      private:
        virtual ::grpc::ClientAsyncResponseReaderInterface<::SetResponse> *
        AsyncSetRaw(::grpc::ClientContext *context, const ::SetRequest &request,
                    ::grpc::CompletionQueue *cq) = 0;
        virtual ::grpc::ClientAsyncResponseReaderInterface<::SetResponse> *
        PrepareAsyncSetRaw(::grpc::ClientContext *context, const ::SetRequest &request,
                           ::grpc::CompletionQueue *cq) = 0;
        virtual ::grpc::ClientAsyncResponseReaderInterface<::GetResponse> *
        AsyncGetRaw(::grpc::ClientContext *context, const ::GetRequest &request,
                    ::grpc::CompletionQueue *cq) = 0;
        virtual ::grpc::ClientAsyncResponseReaderInterface<::GetResponse> *
        PrepareAsyncGetRaw(::grpc::ClientContext *context, const ::GetRequest &request,
                           ::grpc::CompletionQueue *cq) = 0;
        virtual ::grpc::ClientAsyncResponseReaderInterface<::DelResponse> *
        AsyncDeleteRaw(::grpc::ClientContext *context, const ::DelRequest &request,
                       ::grpc::CompletionQueue *cq) = 0;
        virtual ::grpc::ClientAsyncResponseReaderInterface<::DelResponse> *
        PrepareAsyncDeleteRaw(::grpc::ClientContext *context, const ::DelRequest &request,
                              ::grpc::CompletionQueue *cq) = 0;
    };
    class Stub final : public StubInterface {
      public:
        Stub(const std::shared_ptr<::grpc::ChannelInterface> &channel,
             const ::grpc::StubOptions &options = ::grpc::StubOptions());
        ::grpc::Status Set(::grpc::ClientContext *context, const ::SetRequest &request,
                           ::SetResponse *response) override;
        std::unique_ptr<::grpc::ClientAsyncResponseReader<::SetResponse>>
        AsyncSet(::grpc::ClientContext *context, const ::SetRequest &request,
                 ::grpc::CompletionQueue *cq) {
            return std::unique_ptr<::grpc::ClientAsyncResponseReader<::SetResponse>>(
                AsyncSetRaw(context, request, cq));
        }
        std::unique_ptr<::grpc::ClientAsyncResponseReader<::SetResponse>>
        PrepareAsyncSet(::grpc::ClientContext *context, const ::SetRequest &request,
                        ::grpc::CompletionQueue *cq) {
            return std::unique_ptr<::grpc::ClientAsyncResponseReader<::SetResponse>>(
                PrepareAsyncSetRaw(context, request, cq));
        }
        ::grpc::Status Get(::grpc::ClientContext *context, const ::GetRequest &request,
                           ::GetResponse *response) override;
        std::unique_ptr<::grpc::ClientAsyncResponseReader<::GetResponse>>
        AsyncGet(::grpc::ClientContext *context, const ::GetRequest &request,
                 ::grpc::CompletionQueue *cq) {
            return std::unique_ptr<::grpc::ClientAsyncResponseReader<::GetResponse>>(
                AsyncGetRaw(context, request, cq));
        }
        std::unique_ptr<::grpc::ClientAsyncResponseReader<::GetResponse>>
        PrepareAsyncGet(::grpc::ClientContext *context, const ::GetRequest &request,
                        ::grpc::CompletionQueue *cq) {
            return std::unique_ptr<::grpc::ClientAsyncResponseReader<::GetResponse>>(
                PrepareAsyncGetRaw(context, request, cq));
        }
        ::grpc::Status Delete(::grpc::ClientContext *context, const ::DelRequest &request,
                              ::DelResponse *response) override;
        std::unique_ptr<::grpc::ClientAsyncResponseReader<::DelResponse>>
        AsyncDelete(::grpc::ClientContext *context, const ::DelRequest &request,
                    ::grpc::CompletionQueue *cq) {
            return std::unique_ptr<::grpc::ClientAsyncResponseReader<::DelResponse>>(
                AsyncDeleteRaw(context, request, cq));
        }
        std::unique_ptr<::grpc::ClientAsyncResponseReader<::DelResponse>>
        PrepareAsyncDelete(::grpc::ClientContext *context, const ::DelRequest &request,
                           ::grpc::CompletionQueue *cq) {
            return std::unique_ptr<::grpc::ClientAsyncResponseReader<::DelResponse>>(
                PrepareAsyncDeleteRaw(context, request, cq));
        }
        class async final : public StubInterface::async_interface {
          public:
            void Set(::grpc::ClientContext *context, const ::SetRequest *request,
                     ::SetResponse *response, std::function<void(::grpc::Status)>) override;
            void Set(::grpc::ClientContext *context, const ::SetRequest *request,
                     ::SetResponse *response, ::grpc::ClientUnaryReactor *reactor) override;
            void Get(::grpc::ClientContext *context, const ::GetRequest *request,
                     ::GetResponse *response, std::function<void(::grpc::Status)>) override;
            void Get(::grpc::ClientContext *context, const ::GetRequest *request,
                     ::GetResponse *response, ::grpc::ClientUnaryReactor *reactor) override;
            void Delete(::grpc::ClientContext *context, const ::DelRequest *request,
                        ::DelResponse *response, std::function<void(::grpc::Status)>) override;
            void Delete(::grpc::ClientContext *context, const ::DelRequest *request,
                        ::DelResponse *response, ::grpc::ClientUnaryReactor *reactor) override;

          private:
            friend class Stub;
            explicit async(Stub *stub) : stub_(stub) {
            }
            Stub *stub() {
                return stub_;
            }
            Stub *stub_;
        };
        class async *async() override {
            return &async_stub_;
        }

      private:
        std::shared_ptr<::grpc::ChannelInterface> channel_;
        class async async_stub_{this};
        ::grpc::ClientAsyncResponseReader<::SetResponse> *
        AsyncSetRaw(::grpc::ClientContext *context, const ::SetRequest &request,
                    ::grpc::CompletionQueue *cq) override;
        ::grpc::ClientAsyncResponseReader<::SetResponse> *
        PrepareAsyncSetRaw(::grpc::ClientContext *context, const ::SetRequest &request,
                           ::grpc::CompletionQueue *cq) override;
        ::grpc::ClientAsyncResponseReader<::GetResponse> *
        AsyncGetRaw(::grpc::ClientContext *context, const ::GetRequest &request,
                    ::grpc::CompletionQueue *cq) override;
        ::grpc::ClientAsyncResponseReader<::GetResponse> *
        PrepareAsyncGetRaw(::grpc::ClientContext *context, const ::GetRequest &request,
                           ::grpc::CompletionQueue *cq) override;
        ::grpc::ClientAsyncResponseReader<::DelResponse> *
        AsyncDeleteRaw(::grpc::ClientContext *context, const ::DelRequest &request,
                       ::grpc::CompletionQueue *cq) override;
        ::grpc::ClientAsyncResponseReader<::DelResponse> *
        PrepareAsyncDeleteRaw(::grpc::ClientContext *context, const ::DelRequest &request,
                              ::grpc::CompletionQueue *cq) override;
        const ::grpc::internal::RpcMethod rpcmethod_Set_;
        const ::grpc::internal::RpcMethod rpcmethod_Get_;
        const ::grpc::internal::RpcMethod rpcmethod_Delete_;
    };
    static std::unique_ptr<Stub>
    NewStub(const std::shared_ptr<::grpc::ChannelInterface> &channel,
            const ::grpc::StubOptions &options = ::grpc::StubOptions());

    class Service : public ::grpc::Service {
      public:
        Service();
        virtual ~Service();
        virtual ::grpc::Status Set(::grpc::ServerContext *context, const ::SetRequest *request,
                                   ::SetResponse *response);
        virtual ::grpc::Status Get(::grpc::ServerContext *context, const ::GetRequest *request,
                                   ::GetResponse *response);
        virtual ::grpc::Status Delete(::grpc::ServerContext *context, const ::DelRequest *request,
                                      ::DelResponse *response);
    };
    template <class BaseClass> class WithAsyncMethod_Set : public BaseClass {
      private:
        void BaseClassMustBeDerivedFromService(const Service * /*service*/) {
        }

      public:
        WithAsyncMethod_Set() {
            ::grpc::Service::MarkMethodAsync(0);
        }
        ~WithAsyncMethod_Set() override {
            BaseClassMustBeDerivedFromService(this);
        }
        // disable synchronous version of this method
        ::grpc::Status Set(::grpc::ServerContext * /*context*/, const ::SetRequest * /*request*/,
                           ::SetResponse * /*response*/) override {
            abort();
            return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
        }
        void RequestSet(::grpc::ServerContext *context, ::SetRequest *request,
                        ::grpc::ServerAsyncResponseWriter<::SetResponse> *response,
                        ::grpc::CompletionQueue *new_call_cq,
                        ::grpc::ServerCompletionQueue *notification_cq, void *tag) {
            ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq,
                                               notification_cq, tag);
        }
    };
    template <class BaseClass> class WithAsyncMethod_Get : public BaseClass {
      private:
        void BaseClassMustBeDerivedFromService(const Service * /*service*/) {
        }

      public:
        WithAsyncMethod_Get() {
            ::grpc::Service::MarkMethodAsync(1);
        }
        ~WithAsyncMethod_Get() override {
            BaseClassMustBeDerivedFromService(this);
        }
        // disable synchronous version of this method
        ::grpc::Status Get(::grpc::ServerContext * /*context*/, const ::GetRequest * /*request*/,
                           ::GetResponse * /*response*/) override {
            abort();
            return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
        }
        void RequestGet(::grpc::ServerContext *context, ::GetRequest *request,
                        ::grpc::ServerAsyncResponseWriter<::GetResponse> *response,
                        ::grpc::CompletionQueue *new_call_cq,
                        ::grpc::ServerCompletionQueue *notification_cq, void *tag) {
            ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq,
                                               notification_cq, tag);
        }
    };
    template <class BaseClass> class WithAsyncMethod_Delete : public BaseClass {
      private:
        void BaseClassMustBeDerivedFromService(const Service * /*service*/) {
        }

      public:
        WithAsyncMethod_Delete() {
            ::grpc::Service::MarkMethodAsync(2);
        }
        ~WithAsyncMethod_Delete() override {
            BaseClassMustBeDerivedFromService(this);
        }
        // disable synchronous version of this method
        ::grpc::Status Delete(::grpc::ServerContext * /*context*/, const ::DelRequest * /*request*/,
                              ::DelResponse * /*response*/) override {
            abort();
            return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
        }
        void RequestDelete(::grpc::ServerContext *context, ::DelRequest *request,
                           ::grpc::ServerAsyncResponseWriter<::DelResponse> *response,
                           ::grpc::CompletionQueue *new_call_cq,
                           ::grpc::ServerCompletionQueue *notification_cq, void *tag) {
            ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq,
                                               notification_cq, tag);
        }
    };
    typedef WithAsyncMethod_Set<WithAsyncMethod_Get<WithAsyncMethod_Delete<Service>>> AsyncService;
    template <class BaseClass> class WithCallbackMethod_Set : public BaseClass {
      private:
        void BaseClassMustBeDerivedFromService(const Service * /*service*/) {
        }

      public:
        WithCallbackMethod_Set() {
            ::grpc::Service::MarkMethodCallback(
                0, new ::grpc::internal::CallbackUnaryHandler<::SetRequest, ::SetResponse>(
                       [this](::grpc::CallbackServerContext *context, const ::SetRequest *request,
                              ::SetResponse *response) {
                           return this->Set(context, request, response);
                       }));
        }
        void SetMessageAllocatorFor_Set(
            ::grpc::MessageAllocator<::SetRequest, ::SetResponse> *allocator) {
            ::grpc::internal::MethodHandler *const handler = ::grpc::Service::GetHandler(0);
            static_cast<::grpc::internal::CallbackUnaryHandler<::SetRequest, ::SetResponse> *>(
                handler)
                ->SetMessageAllocator(allocator);
        }
        ~WithCallbackMethod_Set() override {
            BaseClassMustBeDerivedFromService(this);
        }
        // disable synchronous version of this method
        ::grpc::Status Set(::grpc::ServerContext * /*context*/, const ::SetRequest * /*request*/,
                           ::SetResponse * /*response*/) override {
            abort();
            return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
        }
        virtual ::grpc::ServerUnaryReactor *Set(::grpc::CallbackServerContext * /*context*/,
                                                const ::SetRequest * /*request*/,
                                                ::SetResponse * /*response*/) {
            return nullptr;
        }
    };
    template <class BaseClass> class WithCallbackMethod_Get : public BaseClass {
      private:
        void BaseClassMustBeDerivedFromService(const Service * /*service*/) {
        }

      public:
        WithCallbackMethod_Get() {
            ::grpc::Service::MarkMethodCallback(
                1, new ::grpc::internal::CallbackUnaryHandler<::GetRequest, ::GetResponse>(
                       [this](::grpc::CallbackServerContext *context, const ::GetRequest *request,
                              ::GetResponse *response) {
                           return this->Get(context, request, response);
                       }));
        }
        void SetMessageAllocatorFor_Get(
            ::grpc::MessageAllocator<::GetRequest, ::GetResponse> *allocator) {
            ::grpc::internal::MethodHandler *const handler = ::grpc::Service::GetHandler(1);
            static_cast<::grpc::internal::CallbackUnaryHandler<::GetRequest, ::GetResponse> *>(
                handler)
                ->SetMessageAllocator(allocator);
        }
        ~WithCallbackMethod_Get() override {
            BaseClassMustBeDerivedFromService(this);
        }
        // disable synchronous version of this method
        ::grpc::Status Get(::grpc::ServerContext * /*context*/, const ::GetRequest * /*request*/,
                           ::GetResponse * /*response*/) override {
            abort();
            return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
        }
        virtual ::grpc::ServerUnaryReactor *Get(::grpc::CallbackServerContext * /*context*/,
                                                const ::GetRequest * /*request*/,
                                                ::GetResponse * /*response*/) {
            return nullptr;
        }
    };
    template <class BaseClass> class WithCallbackMethod_Delete : public BaseClass {
      private:
        void BaseClassMustBeDerivedFromService(const Service * /*service*/) {
        }

      public:
        WithCallbackMethod_Delete() {
            ::grpc::Service::MarkMethodCallback(
                2, new ::grpc::internal::CallbackUnaryHandler<::DelRequest, ::DelResponse>(
                       [this](::grpc::CallbackServerContext *context, const ::DelRequest *request,
                              ::DelResponse *response) {
                           return this->Delete(context, request, response);
                       }));
        }
        void SetMessageAllocatorFor_Delete(
            ::grpc::MessageAllocator<::DelRequest, ::DelResponse> *allocator) {
            ::grpc::internal::MethodHandler *const handler = ::grpc::Service::GetHandler(2);
            static_cast<::grpc::internal::CallbackUnaryHandler<::DelRequest, ::DelResponse> *>(
                handler)
                ->SetMessageAllocator(allocator);
        }
        ~WithCallbackMethod_Delete() override {
            BaseClassMustBeDerivedFromService(this);
        }
        // disable synchronous version of this method
        ::grpc::Status Delete(::grpc::ServerContext * /*context*/, const ::DelRequest * /*request*/,
                              ::DelResponse * /*response*/) override {
            abort();
            return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
        }
        virtual ::grpc::ServerUnaryReactor *Delete(::grpc::CallbackServerContext * /*context*/,
                                                   const ::DelRequest * /*request*/,
                                                   ::DelResponse * /*response*/) {
            return nullptr;
        }
    };
    typedef WithCallbackMethod_Set<WithCallbackMethod_Get<WithCallbackMethod_Delete<Service>>>
        CallbackService;
    typedef CallbackService ExperimentalCallbackService;
    template <class BaseClass> class WithGenericMethod_Set : public BaseClass {
      private:
        void BaseClassMustBeDerivedFromService(const Service * /*service*/) {
        }

      public:
        WithGenericMethod_Set() {
            ::grpc::Service::MarkMethodGeneric(0);
        }
        ~WithGenericMethod_Set() override {
            BaseClassMustBeDerivedFromService(this);
        }
        // disable synchronous version of this method
        ::grpc::Status Set(::grpc::ServerContext * /*context*/, const ::SetRequest * /*request*/,
                           ::SetResponse * /*response*/) override {
            abort();
            return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
        }
    };
    template <class BaseClass> class WithGenericMethod_Get : public BaseClass {
      private:
        void BaseClassMustBeDerivedFromService(const Service * /*service*/) {
        }

      public:
        WithGenericMethod_Get() {
            ::grpc::Service::MarkMethodGeneric(1);
        }
        ~WithGenericMethod_Get() override {
            BaseClassMustBeDerivedFromService(this);
        }
        // disable synchronous version of this method
        ::grpc::Status Get(::grpc::ServerContext * /*context*/, const ::GetRequest * /*request*/,
                           ::GetResponse * /*response*/) override {
            abort();
            return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
        }
    };
    template <class BaseClass> class WithGenericMethod_Delete : public BaseClass {
      private:
        void BaseClassMustBeDerivedFromService(const Service * /*service*/) {
        }

      public:
        WithGenericMethod_Delete() {
            ::grpc::Service::MarkMethodGeneric(2);
        }
        ~WithGenericMethod_Delete() override {
            BaseClassMustBeDerivedFromService(this);
        }
        // disable synchronous version of this method
        ::grpc::Status Delete(::grpc::ServerContext * /*context*/, const ::DelRequest * /*request*/,
                              ::DelResponse * /*response*/) override {
            abort();
            return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
        }
    };
    template <class BaseClass> class WithRawMethod_Set : public BaseClass {
      private:
        void BaseClassMustBeDerivedFromService(const Service * /*service*/) {
        }

      public:
        WithRawMethod_Set() {
            ::grpc::Service::MarkMethodRaw(0);
        }
        ~WithRawMethod_Set() override {
            BaseClassMustBeDerivedFromService(this);
        }
        // disable synchronous version of this method
        ::grpc::Status Set(::grpc::ServerContext * /*context*/, const ::SetRequest * /*request*/,
                           ::SetResponse * /*response*/) override {
            abort();
            return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
        }
        void RequestSet(::grpc::ServerContext *context, ::grpc::ByteBuffer *request,
                        ::grpc::ServerAsyncResponseWriter<::grpc::ByteBuffer> *response,
                        ::grpc::CompletionQueue *new_call_cq,
                        ::grpc::ServerCompletionQueue *notification_cq, void *tag) {
            ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq,
                                               notification_cq, tag);
        }
    };
    template <class BaseClass> class WithRawMethod_Get : public BaseClass {
      private:
        void BaseClassMustBeDerivedFromService(const Service * /*service*/) {
        }

      public:
        WithRawMethod_Get() {
            ::grpc::Service::MarkMethodRaw(1);
        }
        ~WithRawMethod_Get() override {
            BaseClassMustBeDerivedFromService(this);
        }
        // disable synchronous version of this method
        ::grpc::Status Get(::grpc::ServerContext * /*context*/, const ::GetRequest * /*request*/,
                           ::GetResponse * /*response*/) override {
            abort();
            return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
        }
        void RequestGet(::grpc::ServerContext *context, ::grpc::ByteBuffer *request,
                        ::grpc::ServerAsyncResponseWriter<::grpc::ByteBuffer> *response,
                        ::grpc::CompletionQueue *new_call_cq,
                        ::grpc::ServerCompletionQueue *notification_cq, void *tag) {
            ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq,
                                               notification_cq, tag);
        }
    };
    template <class BaseClass> class WithRawMethod_Delete : public BaseClass {
      private:
        void BaseClassMustBeDerivedFromService(const Service * /*service*/) {
        }

      public:
        WithRawMethod_Delete() {
            ::grpc::Service::MarkMethodRaw(2);
        }
        ~WithRawMethod_Delete() override {
            BaseClassMustBeDerivedFromService(this);
        }
        // disable synchronous version of this method
        ::grpc::Status Delete(::grpc::ServerContext * /*context*/, const ::DelRequest * /*request*/,
                              ::DelResponse * /*response*/) override {
            abort();
            return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
        }
        void RequestDelete(::grpc::ServerContext *context, ::grpc::ByteBuffer *request,
                           ::grpc::ServerAsyncResponseWriter<::grpc::ByteBuffer> *response,
                           ::grpc::CompletionQueue *new_call_cq,
                           ::grpc::ServerCompletionQueue *notification_cq, void *tag) {
            ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq,
                                               notification_cq, tag);
        }
    };
    template <class BaseClass> class WithRawCallbackMethod_Set : public BaseClass {
      private:
        void BaseClassMustBeDerivedFromService(const Service * /*service*/) {
        }

      public:
        WithRawCallbackMethod_Set() {
            ::grpc::Service::MarkMethodRawCallback(
                0,
                new ::grpc::internal::CallbackUnaryHandler<::grpc::ByteBuffer, ::grpc::ByteBuffer>(
                    [this](::grpc::CallbackServerContext *context,
                           const ::grpc::ByteBuffer *request, ::grpc::ByteBuffer *response) {
                        return this->Set(context, request, response);
                    }));
        }
        ~WithRawCallbackMethod_Set() override {
            BaseClassMustBeDerivedFromService(this);
        }
        // disable synchronous version of this method
        ::grpc::Status Set(::grpc::ServerContext * /*context*/, const ::SetRequest * /*request*/,
                           ::SetResponse * /*response*/) override {
            abort();
            return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
        }
        virtual ::grpc::ServerUnaryReactor *Set(::grpc::CallbackServerContext * /*context*/,
                                                const ::grpc::ByteBuffer * /*request*/,
                                                ::grpc::ByteBuffer * /*response*/) {
            return nullptr;
        }
    };
    template <class BaseClass> class WithRawCallbackMethod_Get : public BaseClass {
      private:
        void BaseClassMustBeDerivedFromService(const Service * /*service*/) {
        }

      public:
        WithRawCallbackMethod_Get() {
            ::grpc::Service::MarkMethodRawCallback(
                1,
                new ::grpc::internal::CallbackUnaryHandler<::grpc::ByteBuffer, ::grpc::ByteBuffer>(
                    [this](::grpc::CallbackServerContext *context,
                           const ::grpc::ByteBuffer *request, ::grpc::ByteBuffer *response) {
                        return this->Get(context, request, response);
                    }));
        }
        ~WithRawCallbackMethod_Get() override {
            BaseClassMustBeDerivedFromService(this);
        }
        // disable synchronous version of this method
        ::grpc::Status Get(::grpc::ServerContext * /*context*/, const ::GetRequest * /*request*/,
                           ::GetResponse * /*response*/) override {
            abort();
            return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
        }
        virtual ::grpc::ServerUnaryReactor *Get(::grpc::CallbackServerContext * /*context*/,
                                                const ::grpc::ByteBuffer * /*request*/,
                                                ::grpc::ByteBuffer * /*response*/) {
            return nullptr;
        }
    };
    template <class BaseClass> class WithRawCallbackMethod_Delete : public BaseClass {
      private:
        void BaseClassMustBeDerivedFromService(const Service * /*service*/) {
        }

      public:
        WithRawCallbackMethod_Delete() {
            ::grpc::Service::MarkMethodRawCallback(
                2,
                new ::grpc::internal::CallbackUnaryHandler<::grpc::ByteBuffer, ::grpc::ByteBuffer>(
                    [this](::grpc::CallbackServerContext *context,
                           const ::grpc::ByteBuffer *request, ::grpc::ByteBuffer *response) {
                        return this->Delete(context, request, response);
                    }));
        }
        ~WithRawCallbackMethod_Delete() override {
            BaseClassMustBeDerivedFromService(this);
        }
        // disable synchronous version of this method
        ::grpc::Status Delete(::grpc::ServerContext * /*context*/, const ::DelRequest * /*request*/,
                              ::DelResponse * /*response*/) override {
            abort();
            return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
        }
        virtual ::grpc::ServerUnaryReactor *Delete(::grpc::CallbackServerContext * /*context*/,
                                                   const ::grpc::ByteBuffer * /*request*/,
                                                   ::grpc::ByteBuffer * /*response*/) {
            return nullptr;
        }
    };
    template <class BaseClass> class WithStreamedUnaryMethod_Set : public BaseClass {
      private:
        void BaseClassMustBeDerivedFromService(const Service * /*service*/) {
        }

      public:
        WithStreamedUnaryMethod_Set() {
            ::grpc::Service::MarkMethodStreamed(
                0, new ::grpc::internal::StreamedUnaryHandler<::SetRequest, ::SetResponse>(
                       [this](::grpc::ServerContext *context,
                              ::grpc::ServerUnaryStreamer<::SetRequest, ::SetResponse> *streamer) {
                           return this->StreamedSet(context, streamer);
                       }));
        }
        ~WithStreamedUnaryMethod_Set() override {
            BaseClassMustBeDerivedFromService(this);
        }
        // disable regular version of this method
        ::grpc::Status Set(::grpc::ServerContext * /*context*/, const ::SetRequest * /*request*/,
                           ::SetResponse * /*response*/) override {
            abort();
            return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
        }
        // replace default version of method with streamed unary
        virtual ::grpc::Status StreamedSet(
            ::grpc::ServerContext *context,
            ::grpc::ServerUnaryStreamer<::SetRequest, ::SetResponse> *server_unary_streamer) = 0;
    };
    template <class BaseClass> class WithStreamedUnaryMethod_Get : public BaseClass {
      private:
        void BaseClassMustBeDerivedFromService(const Service * /*service*/) {
        }

      public:
        WithStreamedUnaryMethod_Get() {
            ::grpc::Service::MarkMethodStreamed(
                1, new ::grpc::internal::StreamedUnaryHandler<::GetRequest, ::GetResponse>(
                       [this](::grpc::ServerContext *context,
                              ::grpc::ServerUnaryStreamer<::GetRequest, ::GetResponse> *streamer) {
                           return this->StreamedGet(context, streamer);
                       }));
        }
        ~WithStreamedUnaryMethod_Get() override {
            BaseClassMustBeDerivedFromService(this);
        }
        // disable regular version of this method
        ::grpc::Status Get(::grpc::ServerContext * /*context*/, const ::GetRequest * /*request*/,
                           ::GetResponse * /*response*/) override {
            abort();
            return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
        }
        // replace default version of method with streamed unary
        virtual ::grpc::Status StreamedGet(
            ::grpc::ServerContext *context,
            ::grpc::ServerUnaryStreamer<::GetRequest, ::GetResponse> *server_unary_streamer) = 0;
    };
    template <class BaseClass> class WithStreamedUnaryMethod_Delete : public BaseClass {
      private:
        void BaseClassMustBeDerivedFromService(const Service * /*service*/) {
        }

      public:
        WithStreamedUnaryMethod_Delete() {
            ::grpc::Service::MarkMethodStreamed(
                2, new ::grpc::internal::StreamedUnaryHandler<::DelRequest, ::DelResponse>(
                       [this](::grpc::ServerContext *context,
                              ::grpc::ServerUnaryStreamer<::DelRequest, ::DelResponse> *streamer) {
                           return this->StreamedDelete(context, streamer);
                       }));
        }
        ~WithStreamedUnaryMethod_Delete() override {
            BaseClassMustBeDerivedFromService(this);
        }
        // disable regular version of this method
        ::grpc::Status Delete(::grpc::ServerContext * /*context*/, const ::DelRequest * /*request*/,
                              ::DelResponse * /*response*/) override {
            abort();
            return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
        }
        // replace default version of method with streamed unary
        virtual ::grpc::Status StreamedDelete(
            ::grpc::ServerContext *context,
            ::grpc::ServerUnaryStreamer<::DelRequest, ::DelResponse> *server_unary_streamer) = 0;
    };
    typedef WithStreamedUnaryMethod_Set<
        WithStreamedUnaryMethod_Get<WithStreamedUnaryMethod_Delete<Service>>>
        StreamedUnaryService;
    typedef Service SplitStreamedService;
    typedef WithStreamedUnaryMethod_Set<
        WithStreamedUnaryMethod_Get<WithStreamedUnaryMethod_Delete<Service>>>
        StreamedService;
};

#endif // GRPC_kv_2eproto__INCLUDED